name: docker build

on:
  push:
  schedule:
    # Run every week on sunday at 4:15 UTC
    - cron: '15 4 * * 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image: [humble, humble-cu118, noetic, noetic-cu118]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: ./build-image.sh ${{ matrix.image }}
      - name: List Docker images
        run: docker images
